---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
SiteConfig:
  extensions: 
    - SocialstreamSiteConfig
SocialstreamController:
  enable_cache: true
Director:
  rules:
    'socialstream//$Action/$ID/$Name': 'SocialstreamController'